### ISSUE TITLE
Basic layout are not rendered properly

### ISSUE THREAD

**Issue by sureshg** [codeyousef/summon#1]
I just tried to run the sample minimal example given in the repo (https://github.com/codeyousef/summon/blob/main/docs/examples/js/js-example/src/jsMain/kotlin/code/yousef/summon/examples/js/MinimalExample.kt). Multiple issues were found with version 0.2.7.

1. Compilation error

```
ple/src/jsMain/kotlin/code/yousef/summon/examples/js/Main.kt:22:36 Unresolved reference 'gap'.
e: file://docs/examples/js/js-example/src/jsMain/kotlin/code/yousef/summon/examples/js/Main.kt:28:36 Unresolved reference 'top'.
e: file:///docs/examples/js/js-example/src/jsMain/kotlin/code/yousef/summon/examples/js/Main.kt:32:35 Unresolved reference 'JsPlatformRenderer'.
```

2. Column is not rendered as expected

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/5ca9ed01-b536-401a-ba24-d8cbde710362" />

**Comment by codeyousef** [comment]
Should be fixed now. Feel free to reopen the issue if you face problems.

**Comment by sureshg** [comment]
`io.github.codeyousef:summon:0.2.8.0` is still not available on Github package. Could you please publish the latest version?

```
> Failed to query the value of task ':kotlinNpmInstall' property 'packageJsonFiles'.
   > Could not resolve all dependencies for configuration ':jsNpmAggregated'.
      > Could not find io.github.codeyousef:summon:0.2.8.0.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/io/github/codeyousef/summon/0.2.8.0/summon-0.2.8.0.pom
          - https://maven.pkg.github.com/codeyousef/summon/io/github/codeyousef/summon/0.2.8.0/summon-0.2.8.0.pom
        Required by:
```
